CREATE TABLE IF NOT EXISTS sa_us_sales.src_us_sales (
    ORDER_ID                  VARCHAR(50),
    CUSTOMER_ID               VARCHAR(50),
    CUSTOMER_FIRST_NAME       VARCHAR(100),
    CUSTOMER_LAST_NAME        VARCHAR(100),
    CUSTOMER_EMAIL            VARCHAR(255),
    ORDER_DT                  VARCHAR(30),
    CUSTOMER_AGE              VARCHAR(20),
    CUSTOMER_GENDER           VARCHAR(20),
    STATE                     VARCHAR(100),
    CITY                      VARCHAR(150),
    CUSTOMER_SEGMENT          VARCHAR(50),
    PRODUCT_ID                VARCHAR(50),
    PRODUCT_CATEGORY          VARCHAR(100),
    PRODUCT_SUBCATEGORY       VARCHAR(100),
    UNIT_PRICE                VARCHAR(30),
    QUANTITY                  VARCHAR(20),
    DISCOUNT_PERCENT          VARCHAR(30),
    DISCOUNT_AMOUNT           VARCHAR(30),
    SHIPPING_COST             VARCHAR(30),
    TAX_AMOUNT                VARCHAR(30),
    ORDER_AMOUNT              VARCHAR(30),
    PAYMENT_METHOD            VARCHAR(50),
    ORDER_STATUS              VARCHAR(50),
    RETURNED                  VARCHAR(20),
    PROFIT_MARGIN_PERCENT     VARCHAR(30),
    PROFIT_MARGIN_AMOUNT      VARCHAR(30),
    SALES_REP_ID              VARCHAR(50),
    SALES_REP_FIRST_NAME      VARCHAR(100),
    SALES_REP_LAST_NAME       VARCHAR(100),
    SALES_REP_EMAIL           VARCHAR(255),
    COST_AMOUNT               VARCHAR(30),
    CHANNEL                   VARCHAR(50),
    SUBCHANNEL                VARCHAR(50),
    insert_date               TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO sa_us_sales.src_us_sales (
    ORDER_ID, CUSTOMER_ID, CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME, CUSTOMER_EMAIL,
    ORDER_DT, CUSTOMER_AGE, CUSTOMER_GENDER, STATE, CITY, CUSTOMER_SEGMENT,
    PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_SUBCATEGORY, UNIT_PRICE, QUANTITY,
    DISCOUNT_PERCENT, DISCOUNT_AMOUNT, SHIPPING_COST, TAX_AMOUNT, ORDER_AMOUNT,
    PAYMENT_METHOD, ORDER_STATUS, RETURNED, PROFIT_MARGIN_PERCENT, PROFIT_MARGIN_AMOUNT,
    SALES_REP_ID, SALES_REP_FIRST_NAME, SALES_REP_LAST_NAME, SALES_REP_EMAIL,
    COST_AMOUNT, CHANNEL, SUBCHANNEL
)
SELECT 
    source.ORDER_ID, source.CUSTOMER_ID, source.CUSTOMER_FIRST_NAME, source.CUSTOMER_LAST_NAME, source.CUSTOMER_EMAIL,
    source.ORDER_DT, source.CUSTOMER_AGE, source.CUSTOMER_GENDER, source.STATE, source.CITY, source.CUSTOMER_SEGMENT,
    source.PRODUCT_ID, source.PRODUCT_CATEGORY, source.PRODUCT_SUBCATEGORY, source.UNIT_PRICE, source.QUANTITY,
    source.DISCOUNT_PERCENT, source.DISCOUNT_AMOUNT, source.SHIPPING_COST, source.TAX_AMOUNT, source.ORDER_AMOUNT,
    source.PAYMENT_METHOD, source.ORDER_STATUS, source.RETURNED, source.PROFIT_MARGIN_PERCENT, source.PROFIT_MARGIN_AMOUNT,
    source.SALES_REP_ID, source.SALES_REP_FIRST_NAME, source.SALES_REP_LAST_NAME, source.SALES_REP_EMAIL,
    source.COST_AMOUNT, source.CHANNEL, source.SUBCHANNEL
FROM (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY ORDER_ID 
            ORDER BY ORDER_DT DESC
        ) as rn
    FROM sa_us_sales.ext_us_sales
) source
WHERE source.rn = 1
  AND NOT EXISTS (
      SELECT 1 
      FROM sa_us_sales.src_us_sales target
      WHERE target.ORDER_ID = source.ORDER_ID
  );


--TEST
SELECT count(*) FROM sa_us_sales.src_us_sales;
SELECT count(*) FROM sa_int_sales.src_int_sales;
