CREATE TABLE IF NOT EXISTS sa_int_sales.src_int_sales (
    ORDER_ID_INT                 VARCHAR(50),
    CUSTOMER_ID_INT              VARCHAR(50),
    CUSTOMER_FIRST_NAME_INT      VARCHAR(100),
    CUSTOMER_LAST_NAME_INT       VARCHAR(100),
    CUSTOMER_EMAIL_INT           VARCHAR(255),
    ORDER_DT_INT                 VARCHAR(30),
    COUNTRY                      VARCHAR(100),
    CITY_INT                     VARCHAR(150),
    CUSTOMER_STATUS              VARCHAR(50),
    PRODUCT_ID_INT               VARCHAR(50),
    CATEGORY                     VARCHAR(100),
    SUBCATEGORY                  VARCHAR(100),
    PRICE                        VARCHAR(30),
    QUANTITY_INT                 VARCHAR(20),
    DISCOUNT_PERCENT_INT         VARCHAR(30),
    DISCOUNT_AMOUNT_INT          VARCHAR(30),
    SHIPPING_COST_INT            VARCHAR(30),
    TAX                          VARCHAR(30),
    ORDER_AMOUNT_INT             VARCHAR(30),
    PAYMENT                      VARCHAR(50),
    ORDER_STATUS_INT             VARCHAR(50),
    RETURNED                     VARCHAR(20),
    PPROFIT_MARGIN_PERCENT_INT   VARCHAR(30),
    PROFIT_AMOUNT_INT            VARCHAR(30),
    SALES_REP_ID_INT             VARCHAR(50),
    SALES_REP_FIRST_NAME_INT     VARCHAR(100),
    SALES_REP_LAST_NAME_INT      VARCHAR(100),
    SALES_REP_EMAIL_INT          VARCHAR(255),
    COST_AMOUNT_INT              VARCHAR(30),
    CHANNEL                      VARCHAR(50),
    SUBCHANNEL                   VARCHAR(50),
    insert_date                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO sa_int_sales.src_int_sales (
    ORDER_ID_INT, CUSTOMER_ID_INT, CUSTOMER_FIRST_NAME_INT, CUSTOMER_LAST_NAME_INT,
    CUSTOMER_EMAIL_INT, ORDER_DT_INT, COUNTRY, CITY_INT, CUSTOMER_STATUS,
    PRODUCT_ID_INT, CATEGORY, SUBCATEGORY, PRICE, QUANTITY_INT, DISCOUNT_PERCENT_INT,
    DISCOUNT_AMOUNT_INT, SHIPPING_COST_INT, TAX, ORDER_AMOUNT_INT, PAYMENT,
    ORDER_STATUS_INT, RETURNED, PPROFIT_MARGIN_PERCENT_INT, PROFIT_AMOUNT_INT,
    SALES_REP_ID_INT, SALES_REP_FIRST_NAME_INT, SALES_REP_LAST_NAME_INT,
    SALES_REP_EMAIL_INT, COST_AMOUNT_INT, CHANNEL, SUBCHANNEL
)
SELECT 
    source.ORDER_ID_INT, source.CUSTOMER_ID_INT, source.CUSTOMER_FIRST_NAME_INT, source.CUSTOMER_LAST_NAME_INT,
    source.CUSTOMER_EMAIL_INT, source.ORDER_DT_INT, source.COUNTRY, source.CITY_INT, source.CUSTOMER_STATUS,
    source.PRODUCT_ID_INT, source.CATEGORY, source.SUBCATEGORY, source.PRICE, source.QUANTITY_INT, source.DISCOUNT_PERCENT_INT,
    source.DISCOUNT_AMOUNT_INT, source.SHIPPING_COST_INT, source.TAX, source.ORDER_AMOUNT_INT, source.PAYMENT,
    source.ORDER_STATUS_INT, source.RETURNED, source.PPROFIT_MARGIN_PERCENT_INT, source.PROFIT_AMOUNT_INT,
    source.SALES_REP_ID_INT, source.SALES_REP_FIRST_NAME_INT, source.SALES_REP_LAST_NAME_INT,
    source.SALES_REP_EMAIL_INT, source.COST_AMOUNT_INT, source.CHANNEL, source.SUBCHANNEL
FROM (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY ORDER_ID_INT 
            ORDER BY ORDER_DT_INT DESC
        ) as rn
    FROM sa_int_sales.ext_int_sales
) source
WHERE source.rn = 1
  AND NOT EXISTS (
      SELECT 1 
      FROM sa_int_sales.src_int_sales target
      WHERE target.ORDER_ID_INT = source.ORDER_ID_INT
  );
