CREATE SCHEMA IF NOT EXISTS bl_cl;
CREATE SCHEMA IF NOT EXISTS bl_3nf;
CREATE SCHEMA IF NOT EXISTS bl_dm;
CREATE SCHEMA IF NOT EXISTS sa_int_sales;
CREATE SCHEMA IF NOT EXISTS sa_us_sales;

CREATE ROLE dwh_user LOGIN PASSWORD 'dwh';

CREATE EXTENSION IF NOT EXISTS file_fdw;
CREATE SERVER IF NOT EXISTS file_server FOREIGN DATA WRAPPER file_fdw;

GRANT USAGE ON SCHEMA sa_int_sales, sa_us_sales, bl_3nf, bl_cl, bl_dm TO dwh_user;
GRANT CREATE ON SCHEMA bl_cl TO dwh_user;


GRANT SELECT ON ALL TABLES IN SCHEMA sa_int_sales, sa_us_sales TO dwh_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA bl_3nf, bl_cl, bl_dm TO dwh_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA bl_3nf, bl_cl, bl_dm TO dwh_user;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA bl_cl TO dwh_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA sa_int_sales, sa_us_sales
    GRANT SELECT ON TABLES TO dwh_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA bl_3nf, bl_cl, bl_dm
    GRANT SELECT, INSERT, UPDATE ON TABLES TO dwh_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA bl_3nf, bl_cl, bl_dm
    GRANT USAGE, SELECT ON SEQUENCES TO修 dwh_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA bl_cl
    GRANT EXECUTE ON ROUTINES TO dwh_user;

SET ROLE dwh_user;

SELECT current_user, current_role; 

RESET ROLE; 